# Generated by Django 3.1.2 on 2020-10-30 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('condation', models.CharField(choices=[('New', 'New'), ('Used', 'Used')], max_length=4)),
                ('created', models.DateTimeField()),
            ],
        ),
    ]
